INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('15 May','15 مايو',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Cairo'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Abdin','عابدين',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Cairo'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Ad-Darb Al-Aḥmar','الدرب الأحمر',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Cairo'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Ain Shams','عين شمس',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Cairo'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Al-Amiria','الاميريه',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Cairo'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Al-Azbakiyah','الأزبكية',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Cairo'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Al-Basatin','البساتين',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Cairo'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Al-Jamaliyah','الجمالية',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Cairo'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Al-khalifa','الخليفة',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Cairo'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Al Maadi','المعادي',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Cairo'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Al-Marj','المرج',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Cairo'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Al-Masarah','المعصره',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Cairo'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Al-Matariyah','المطرية',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Cairo'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Al-Muqattam','المقطم',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Cairo'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Al-Muski','الموسكي',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Cairo'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('New Cairo','القاهرة الجديدة',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Cairo'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Al-Wayli','الوايلي',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Cairo'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Al-Nozha','النزهة',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Cairo'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Ash-Sharabiyah','الشرابية',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Cairo'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Ash-Shuruq','الشروق',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Cairo'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('As-Sahel','الساحل',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Cairo'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('As-Salam','السلام',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Cairo'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('As-Sayidah Zaynab','السيدة زينب',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Cairo'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Attbin','التبين',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Cairo'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Az-Zahir','الظاهر',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Cairo'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Zamalek','الزمالك',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Cairo'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Az-Zawiyah Al-Hamra','الزاوية الحمراء',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Cairo'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Zeitoun','الزيتون',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Cairo'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Bab Ash-Shariyah','باب الشعرية',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Cairo'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Bulaq','بولاق',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Cairo'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Dar As-Salam','دار السلام',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Cairo'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Hada ''iq Al-Qubbah','حدائق القبة',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Cairo'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Helwan','حلوان',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Cairo'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Nasr City','مدينة نصر',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Cairo'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Badr','مدينة بدر',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Cairo'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Heliopolis','مصر الجديدة',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Cairo'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Old Cairo','مصر القديمة',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Cairo'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Manshiyat Naser','منشأة ناصر',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Cairo'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Qasr An-Nil','قصر النيل',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Cairo'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Rod El Farag','روض الفرج',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Cairo'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Shubra','شبرا',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Cairo'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Tura','طره',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Cairo'));





INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Dokki','الدقي',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Al-Jizah'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Al-Ahram','الأهرام',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Al-Jizah'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Al-Ajuzah','العجوزة',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Al-Jizah'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Badrashein','البدرشين',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Al-Jizah'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Al-Hawamidiyah','الحوامدية',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Al-Jizah'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Giza','الجيزة',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Al-Jizah'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Al-Umraniyah','العمرانية',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Al-Jizah'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Al-Warraq','الوراق',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Al-Jizah'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Sheikh Zayed City','الشيخ زايد',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Al-Jizah'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('At-Talbiah','الطالبيه',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Al-Jizah'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Markaz Ossim','مركز أوسيم',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Al-Jizah'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Bulaq Al-Dakrur','بولاق الدكرور',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Al-Jizah'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Imbaba','امبابة',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Al-Jizah'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Kirdasah','كرداسة',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Al-Jizah'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('6th of October City','6 أكتوبر',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Al-Jizah'));


INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Dekhela','الدخيلة',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Alexandria'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Amreya','العامرية',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Alexandria'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Ataren','العطارين',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Alexandria'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Gomrok','الجمرك',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Alexandria'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Labban','اللبان',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Alexandria'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Mansheya','المنشية',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Alexandria'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Montaza','المنتزة',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Alexandria'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('El Raml','الرمل',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Alexandria'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('North Coast','الساحل الشمالى',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Alexandria'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Bab Sharqi','باب شرقى',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Alexandria'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Borg El Arab','برج العرب',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Alexandria'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Karmouz','كرموز',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Alexandria'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('New Borg El Arab','برج العرب الجديده',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Alexandria'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Port Al-Basal','مينا البصل',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Alexandria'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Moharam Bek','محرم بك',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Alexandria'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Sidi Gaber','سيدى جابر',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Alexandria'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Sidi Bishr','سيدى بشر',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Alexandria'));





INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Abu Simbel',' أبو سنبل',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Aswan'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Aswan','مركز أسوان',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Aswan'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Daraw','مركز دراو',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Aswan'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Edfu','مركز أدفو',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Aswan'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Kom Ombo','مركز كوم امبو',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Aswan'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('New Aswan','مدينة أسوان الجديدة',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Aswan'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('New Tushka','مدينة توشكى الجديدة',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Aswan'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Nasser City','مركز نصر',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Aswan'));



INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Abnub','مركز أبنوب',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Asyut'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Abu Tig','أبوتيج',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Asyut'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('El Badari','مركز البدارى',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Asyut'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('El Fath','مركز الفتح',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Asyut'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('El Ghanayem','مركز الغنايم',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Asyut'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('El Qusiya','مركز القوصية',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Asyut'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Asyut','مركز أسيوط',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Asyut'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Asyut 1','قسم أسيوط',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Asyut'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Dairut','مركز ديروط',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Asyut'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('New Asyut','مدينة اسيوط الجديدة',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Asyut'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Manfalut','مركز منفلوط',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Asyut'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Sahel Selim','مركز ساحل سليم',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Asyut'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Sodfa','مركز صدفا',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Asyut'));


INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('El Fashn','مركز الفشن',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Bani Suwayf'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('El Wasta','مركز الواسطى',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Bani Suwayf'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Beni Suef','بنى سويف',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Bani Suwayf'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Biba','مركز ببا',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Bani Suwayf'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Ihnasiya','مركز أهناسيا',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Bani Suwayf'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('New Beni Suef','مدينة بنى سويف الجديدة',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Bani Suwayf'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Nasser','مركز ناصر',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Bani Suwayf'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Sumusta El Waqf','مركز سمسطا',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Bani Suwayf'));



INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('El Dawahy','الضواحى',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Port Said'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('El Arab','العرب',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Port Said'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('El Ganoub','الجنوب',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Port Said'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('El Manakh','المناخ',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Port Said'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('El Manasra','المناصرة',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Port Said'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('El Sharq','الشرق',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Port Said'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('El Zohur','الزهور',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Port Said'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Port Fuad','بورفؤاد',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Port Said'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Police Department Port Said','إدارة شرطة ميناء بورسعيد',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Port Said'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Mubarak East','قسم مبارك - شرق التفريعة',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Port Said'));

INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('El Zarqa','الزرقا',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Dumyat'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Markaz Damietta','مركز دمياط',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Dumyat'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Qsm Damietta','قسم دمياط',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Dumyat'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Faraskur','فارسكور',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Dumyat'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Police Dept. Port of Damietta','إداره شرطه ميناء دمياط الجديد',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Dumyat'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Kafr El Batik','كفر البطيخ',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Dumyat'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Kafr Saad','كفر سعد',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Dumyat'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('New Damietta','مدينه دمياط الجديده',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Dumyat'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Ras El Bar','رأس البر',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Dumyat'));



INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('El Dabaa','قسم الضبعة',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Matruh'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('El Alamein','قسم العلمين',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Matruh'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('El Hamam','قسم الحمام',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Matruh'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('El Negaila','قسم النجيله',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Matruh'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('North Coast','قسم الساحل الشمالى',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Matruh'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Sallum','قسم السلوم',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Matruh'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Mersa Matruh','قسم مرسى مطروح',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Matruh'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Sidi Barrani','قسم سيدى برانى',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Matruh'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Siwa Oasis','قسم سيوة',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Matruh'));


INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Aga','مركز أجا',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Ad Daqahliyah'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('El Gamaliya','مركز الجمالية',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Ad Daqahliyah'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('El Kurdi','قسم الكردى',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Ad Daqahliyah'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('El Mansoura','مركز المنصورة',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Ad Daqahliyah'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('El Mansoura 1','قسم اول المنصورة',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Ad Daqahliyah'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('El Mansoura 2','قسم ثان المنصورة',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Ad Daqahliyah'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('El Manzala','مركز المنزلة',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Ad Daqahliyah'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('El Matareya','مركز المطرية',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Ad Daqahliyah'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('El Senbellawein','مركز السنبلاوين',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Ad Daqahliyah'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Beni Ebeid','مركز بنى عبيد',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Ad Daqahliyah'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Belqas','مركز بلقاس',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Ad Daqahliyah'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Dikirnis','مركز دكرنس',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Ad Daqahliyah'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Gamasa','قسم جمصة',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Ad Daqahliyah'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Maḥallat Damanah','مركز محلة دمنة',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Ad Daqahliyah'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Minyet El Nasr','مركز منية النصر',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Ad Daqahliyah'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Mit Ghamr','قسم ميت غمر',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Ad Daqahliyah'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Mit Salsil','مركز ميت سلسيل',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Ad Daqahliyah'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Nabaroh','مركز نبروة',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Ad Daqahliyah'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Shirbin','مركز شربين',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Ad Daqahliyah'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Talkha','مركز طلخا',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Ad Daqahliyah'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Timay El Imdid','مركز تمى الأمديد',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Ad Daqahliyah'));



INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('El Mahalla El Kubra','مركز المحله الكبرى',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Al Gharbiyah'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('El Santa','مركز السنطة',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Al Gharbiyah'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Basyoun','مركز بسيون',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Al Gharbiyah'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Kafr El Zayat','مركز كفر الزيات',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Al Gharbiyah'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Kotoor','مركز قطور',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Al Gharbiyah'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Samanoud','مركز سمنود',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Al Gharbiyah'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Tanta','طنطا',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Al Gharbiyah'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Zefta','قسم زفتى',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Al Gharbiyah'));




INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Abu Tesht','مركز أبو طشت',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Qina'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('El Waqf','مركز الوقف',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Qina'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Dishna','مركز دشنا',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Qina'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Farshut','مركز فرشوط',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Qina'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('New Qena','مدينة قنا الجديدة',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Qina'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Nag Hammadi','مركز نجع حمادى',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Qina'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Naqada','مركز نقادة',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Qina'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Gebtu or Coptos','مركز قفط',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Qina'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Qena','قسم قنا',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Qina'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Qus','مركز قوص',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Qina'));



INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Akhmim','مركز أخميم',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Sohag'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('El Balyana','مركز البلينا',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Sohag'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('El Kawtar','قسم الكوثر',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Sohag'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('El Maragha','مركز المراغة',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Sohag'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('El Munsha','مركز المنشأة',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Sohag'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Aserat','مركز العسيرات',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Sohag'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Dar El Salam','مركز دار السلام',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Sohag'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Girga','قسم جرجا',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Sohag'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Juhaynah West','مركز جهينة الغربية',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Sohag'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('New Akhmim','مدينة أخميم الجديدة',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Sohag'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('New Sohag','مدينة سوهاج الجديدة',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Sohag'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Saqultah','مركز ساقلته',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Sohag'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Sohag','مركز سوهاج',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Sohag'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Tahta','قسم طهطا',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Sohag'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Tima','مركز طما',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Sohag'));




INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Abu Radis','أبو رديس',(SELECT ID from CITY WHERE CITY.NAME_EN = 'South Sinai'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('El Tor','الطور',(SELECT ID from CITY WHERE CITY.NAME_EN = 'South Sinai'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Dahab','دهب',(SELECT ID from CITY WHERE CITY.NAME_EN = 'South Sinai'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Nuweiba','نويبع',(SELECT ID from CITY WHERE CITY.NAME_EN = 'South Sinai'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Ras Sidr','رأس سدر',(SELECT ID from CITY WHERE CITY.NAME_EN = 'South Sinai'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Saint Catherine','سانت كاترين',(SELECT ID from CITY WHERE CITY.NAME_EN = 'South Sinai'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Sharm El Sheikh','شرم الشيخ',(SELECT ID from CITY WHERE CITY.NAME_EN = 'South Sinai'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Taba','طابا',(SELECT ID from CITY WHERE CITY.NAME_EN = 'South Sinai'));




INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('El Arish','العريش',(SELECT ID from CITY WHERE CITY.NAME_EN = 'North Sinai'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('El Hassana','الحسنة',(SELECT ID from CITY WHERE CITY.NAME_EN = 'North Sinai'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Sheikh Zuweid','الشيخ زويد',(SELECT ID from CITY WHERE CITY.NAME_EN = 'North Sinai'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Bir El Abd','بئر العبد',(SELECT ID from CITY WHERE CITY.NAME_EN = 'North Sinai'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Nakhl','نخل',(SELECT ID from CITY WHERE CITY.NAME_EN = 'North Sinai'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Rafah','رفح',(SELECT ID from CITY WHERE CITY.NAME_EN = 'North Sinai'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Shurtet El Qasima','قسم شرطة القسيمة',(SELECT ID from CITY WHERE CITY.NAME_EN = 'North Sinai'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Shurtet Rumana','قسم شرطة رمانة',(SELECT ID from CITY WHERE CITY.NAME_EN = 'North Sinai'));



INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Hurghada','الغردقة',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Red Sea'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('El Qoseir','القصير',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Red Sea'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Shalateen','الشلاتين',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Red Sea'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Hala''ib','حلايب',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Red Sea'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Marsa Alam','مرسى علم',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Red Sea'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Ras Gharib','رأس غارب',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Red Sea'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Safaga','سفاجا',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Red Sea'));




INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Abu El Matamir','ابو المطامير',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Al-Buhayrah'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Abu Hummus','ابوحمص',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Al-Buhayrah'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('El Delengat','الدلنجات',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Al-Buhayrah'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Mahmoudiyah','المحمودية',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Al-Buhayrah'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Rahmaniya','الرحمانية',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Al-Buhayrah'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Badr','بدر',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Al-Buhayrah'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Damanhour','دمنهور',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Al-Buhayrah'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('West Nubariyah','غرب النوبارية',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Al-Buhayrah'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Hosh Essa','حوش عيسى',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Al-Buhayrah'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Edku','إدكو',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Al-Buhayrah'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Itay El Barud','إيتاى البارود',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Al-Buhayrah'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Kafr El Dawwar','كفر الدوار',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Al-Buhayrah'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Kom Hamada','كوم حمادة',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Al-Buhayrah'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Rosetta','رشيد',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Al-Buhayrah'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Shubrakhit','شبراخيت',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Al-Buhayrah'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Natrn Valley','وادى النطرون',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Al-Buhayrah'));



INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Faiyum','مركز الفيوم',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Al-Fayyum'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Ibsheway','مركز أبشواى',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Al-Fayyum'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Itsa','مركز أطسا',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Al-Fayyum'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('New Faiyum','مدينة الفيوم الجديدة',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Al-Fayyum'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Sinnuris','مركز سنورس',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Al-Fayyum'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Tamiya','مركز طامية',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Al-Fayyum'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Yousef El Seddik','مركز يوسف الصديق',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Al-Fayyum'));




INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Burullus','مركز البرلس',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Kafr-ash-Shaykh'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('El Hamool','مركز الحامول',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Kafr-ash-Shaykh'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('El Reyad','مركز الرياض',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Kafr-ash-Shaykh'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Bila','قسم بيلا',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Kafr-ash-Shaykh'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Desouk','قسم دسوق',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Kafr-ash-Shaykh'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Fuwa','مركز فوه',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Kafr-ash-Shaykh'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Kafr el Sheikh','كفر الشيخ',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Kafr-ash-Shaykh'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Metoubes','مركز مطوبس',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Kafr-ash-Shaykh'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Qallin','مركز قلين',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Kafr-ash-Shaykh'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Sidi Salem','مركز سيدى سالم',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Kafr-ash-Shaykh'));


INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Abu Suwir','مركز ابو صوير',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Al-Ismailiyah'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Ismailia','مركز الاسماعيلية',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Al-Ismailiyah'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('El Qantara','مركز القنطرة',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Al-Ismailiyah'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('El Qantara El Sharqiya','قسم القنطرة شرق',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Al-Ismailiyah'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('New Kasaseen','مركز القصاصين الجديده',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Al-Ismailiyah'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Tell El Kebir','مركز التل الكبير',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Al-Ismailiyah'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Fayid','مركز فايد',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Al-Ismailiyah'));



INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('El Bagour','مركز الباجور',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Al-Minufiyah'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Ashmoun','مركز أشمون',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Al-Minufiyah'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('El Shohada','مركز الشهداء',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Al-Minufiyah'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Birket el Sab','مركز بركة السبع',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Al-Minufiyah'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Sadat City','مدينة السادات',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Al-Minufiyah'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Menouf','مدينة منوف',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Al-Minufiyah'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Quweisna','مركز قويسنا',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Al-Minufiyah'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Shibin el Kom','مركز شبين الكوم',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Al-Minufiyah'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Sers El Lyan','قسم سرس الليانة',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Al-Minufiyah'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Tala','مركز تلا',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Al-Minufiyah'));



INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Abu Qirqas','مركز ابو قرقاص',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Al-Minya'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('El Idwa','مركز العدوة',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Al-Minya'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Minya','مركز المنيا',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Al-Minya'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Beni Mazar','مركز بنى مزار',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Al-Minya'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Deir Mawas','مركز دير مواس',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Al-Minya'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('New Minya','مدينة المنيا الجديدة',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Al-Minya'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Maghagha','مركز مغاغة',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Al-Minya'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Malawit Gharb','مركز سمالوط غرب',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Al-Minya'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Mallawi','مركز ملوى',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Al-Minya'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Matai','مركز مطاى',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Al-Minya'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Samalut','مركز سمالوط',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Al-Minya'));


/*Done */

/*new */



INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Khanka','الخانكه',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Al-Qalyubiyah'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Khusus','الخصوص',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Al-Qalyubiyah'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('El Qanater El Khayreya','القناطر الخيرية',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Al-Qalyubiyah'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('El Ubour','العبور',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Al-Qalyubiyah'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Banha','بنها',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Al-Qalyubiyah'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Kafr Shukr','كفر شكر',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Al-Qalyubiyah'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Qaha','قها',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Al-Qalyubiyah'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Qalyub','قليوب',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Al-Qalyubiyah'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Shubra El Kheima','شبرا الخيمة',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Al-Qalyubiyah'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Shibin El Qanater','شبين القناطر',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Al-Qalyubiyah'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Tukh','طوخ',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Al-Qalyubiyah'));




INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Qurna','القرنه',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Luxor'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Luxor','الأقصر',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Luxor'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Armant','أرمنت',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Luxor'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Esna','إسنا',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Luxor'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Tiba','طيبة',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Luxor'));



INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Kharga','قسم الواحات الخارجة',(SELECT ID from CITY WHERE CITY.NAME_EN = 'New Valley'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Balat','مركز بلاط',(SELECT ID from CITY WHERE CITY.NAME_EN = 'New Valley'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Dakhla','مركز الداخلة',(SELECT ID from CITY WHERE CITY.NAME_EN = 'New Valley'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Farafra','مركز الفرافرة',(SELECT ID from CITY WHERE CITY.NAME_EN = 'New Valley'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Baris','مركز باريس',(SELECT ID from CITY WHERE CITY.NAME_EN = 'New Valley'));



INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Arbaeen','قسم الأربعين',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Suez'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Ganayen','قسم الجناين',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Suez'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Suez','قسم السويس',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Suez'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Attaka','قسم عتاقة',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Suez'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Faisal','قسم فيصل',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Suez'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Port Suez Police Department','إدارة شرطة ميناء السويس',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Suez'));



INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Abu Hammad','مركز أبو حماد',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Ash-Sharqiyah'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Abu Kebir','مركز أبوكبير',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Ash-Sharqiyah'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('El Husseiniya','مركز الحسينية',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Ash-Sharqiyah'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('El Ibrahimiya','مركز الأبراهيمية',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Ash-Sharqiyah'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('El Qanayat','قسم القنايات',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Ash-Sharqiyah'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('El Qurein','قسم القرين',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Ash-Sharqiyah'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('New Salhia','قسم الصالحية الجديدة',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Ash-Sharqiyah'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Awlad Saqr','مركز أولاد صقر',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Ash-Sharqiyah'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Zagazig','مركز الزقازيق',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Ash-Sharqiyah'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Bilbeis','مركز بلبيس',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Ash-Sharqiyah'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Diyarb Negm','مركز ديرب نجم',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Ash-Sharqiyah'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Faqous','مركز فاقوس',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Ash-Sharqiyah'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Hihya','مركز ههيا',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Ash-Sharqiyah'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Kafr Saqr','مركز كفر صقر',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Ash-Sharqiyah'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('10th of Ramadan City','قسم مدينة عشرة رمضان',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Ash-Sharqiyah'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Mashtool El Souk','مركز مشتول السوق',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Ash-Sharqiyah'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Minya El Qamh','مركز منيا القمح',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Ash-Sharqiyah'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Minshat Abu Omar','مركز منشاه ابوعمر',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Ash-Sharqiyah'));
INSERT INTO DISTRICT(NAME_EN, NAME_AR, CITY_ID) VALUES ('Tanis','مركز صان الحجر',(SELECT ID from CITY WHERE CITY.NAME_EN = 'Ash-Sharqiyah'));








